services:
  - type: web
    name: song-splitter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    disk:
      name: storage
      mountPath: /opt/render/project/src/storage
      sizeGB: 1 