services:
  - type: web
    name: song-splitter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 2 --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true
    disk:
      name: song-splitter-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 